### ISSUE TITLE
Bug Report: When I attempt to apply the Mount Retrofitting to the Improved Armaments Flex mount on a mech, it instead applies it to the mount already attached to the mech.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#403] opened 2019-10-29 17:47 UTC
<strong>Submitted At: </strong>10/29/2019 12:47:02
<strong>Platform: </strong>OSX
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>When I attempt to apply the Mount Retrofitting to the Improved Armaments Flex mount on a mech, it instead applies it to the mount already attached to the mech.
<strong>Reproduction Steps: </strong>Took the Improved Armament and Mount Retrofitting cores, and two license ranks for the Kobold frame. When I choose the option to change the Flex mount to a Main/Aux, nothing seems to change, and I have to remove the effect from the Main/Aux mount the Kobold already has
<strong>Contact Info: </strong>@cylonspy#7719

**Comment by aritsune** [comment] 2020-01-02 00:02
Duplicate of #435

**Closed by aritsune** 2020-01-02 00:02 UTC
Labels: bug
