### ISSUE TITLE
[BUG] Can't access Pilot Roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1779] opened 2021-12-11 00:48 UTC
<strong>Submitted At: </strong> 12/10/2021 18:48:04<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When trying to enter the Pilot Roster, I received the error notification "e.pilotIDs is undefined", and the screen/roster does not load or appear.<br><br><strong>Reproduction Steps:<br> </strong> I have 10+ pilots stored, several LCPs loaded.  When loading from a recent .compcon backup, the issue reappears. Issue persists when I log out/refresh/clear cache, but not when I open comp/con a firefox incognito window and log in.<br><br><strong>Expected Result:<br> </strong> The pilot roster should load, and i should be able to access my pilots.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
va/<@https://compcon.app/app.bundle.js:343:220523
ge@https://compcon.app/app.bundle.js:22:15925
va@https://compcon.app/app.bundle.js:343:220004
t.prototype._render@https://compcon.app/app.bundle.js:22:35296
i@https://compcon.app/app.bundle.js:22:64441
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
n@https://compcon.app/app.bundle.js:22:23167
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
lo@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
n@https://compcon.app/app.bundle.js:22:23167
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
S/<@https://compcon.app/app.bundle.js:22:55650
S@https://compcon.app/app.bundle.js:22:55834
S/<@https://compcon.app/app.bundle.js:22:55359
S@https://compcon.app/app.bundle.js:22:55834
lo@https://compcon.app/app.bundle.js:22:56970
t.prototype._update@https://compcon.app/app.bundle.js:22:34334
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un.prototype.run@https://compcon.app/app.bundle.js:22:27494
pn@https://compcon.app/app.bundle.js:22:25602
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
```<br>

**Comment by msprijatelj** [comment] 2021-12-11 01:51
Duplicate of #1777

**Closed by msprijatelj** 2021-12-11 01:51 UTC
Labels: bug, triage, app
