### ISSUE TITLE
[BUG] new rolling menu UI is broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1406] opened 2021-04-26 19:29 UTC
<strong>Submitted At: </strong>4/26/2021 14:29:09
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When using a mech in active play, a context menu now pops up that not only has redundant input options to interact with but also leaves the "commit roll" button offscreen despite scrolling efforts. I have to zoom out below 100% to make it visible, which in turn makes the text quite small.
<strong>To Reproduce: </strong>
High-DPI monitor, Firefox, Rolled an attack with 1 accuracy through the active combat interface.
<strong>Expected behavior: </strong>
Please make the menu position itself so that the commit roll button is visible at 100% zoom on High-DPI monitors. I think my graphics driver might be scaling apps to 1.5 in order for font to be of a reasonable size on my relatively small screen.
<strong>Additional context: </strong>
Here is a gif of what my UI experience is like: https://imgur.com/a/m7bM0jE
<strong>Contact Info: </strong>
Discord: abcde#0203
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-06-04 16:14
duplicate of #1402

**Closed by jarena3** 2021-06-04 16:14 UTC
Labels: bug, triage
