### ISSUE TITLE
[BUG] Copies of encounters/npcs/etc affect the original

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1814] opened 2022-01-03 16:45 UTC
<strong>Submitted At: </strong> 1/3/2022 10:45:48<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Oftentimes, making a copy of an encounter, npc, mission, etc and editing it results in the ORIGINAL having the same changes. For instance, I copied a mission to keep its sitrep description, then changed its enemies. When I look back at the first one for reference, all the enemies are the same.<br><br><strong>Reproduction Steps:<br> </strong> Copy an encounter or NPC, change the copy (not the original). I don't know how to replicate it consistently beyond trying that.<br><br><strong>Expected Result:<br> </strong> Changing an encounter SHOULD NEVER affect another encounter. This causes significant data and content loss.<br><br><strong>Additional Context:<br> </strong> This is just a complaint but the sheer amount of data loss this app has is making me extremely unsatisfied with Lancer (since it has too much crunch to play without a companion app). I've had nonstop issues with the cloud saves and backup saves, and now even so much as making copies of things ruins the original.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-01-03 21:01
Duplicate of #1339

**Closed by msprijatelj** 2022-01-03 21:01 UTC
Labels: bug, triage, app
