### ISSUE TITLE
[BUG] unable to verify account

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1881] opened 2022-03-16 03:30 UTC
<strong>Submitted At: </strong> 3/15/2022 22:29:56<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> it says i need to verify my account but there is no place to put in the verification code received by email<br><br><strong>Reproduction Steps:<br> </strong> quit out of verification message<br><br><strong>Expected Result:<br> </strong> I would still be able to verify account even if I clicked out of the verification message<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-03-17 00:58
Start to enter your Email address and a “Have a verification code?” message will pop up underneath the input. Click that and you’ll be able to verify your account. 

Otherwise, duplicate of #1864.

**Closed by msprijatelj** 2022-03-17 00:58 UTC
Labels: bug, triage, app
