### ISSUE TITLE
[BUG] Pilot roster fails to open after updating and reloading

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1782] opened 2021-12-11 03:14 UTC
<strong>Submitted At: </strong> 12/10/2021 21:14:13<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The pilot roster will not open, consistently throwing an undefined length error<br><br><strong>Reproduction Steps:<br> </strong> Update COMP/CON using the top-right update and reload button, then attempt to open the pilot roster<br><br><strong>Expected Result:<br> </strong> The pilot roster is expected to open and display saved pilots<br><br><strong>Additional Context:<br> </strong> version: 2.2.35<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)```<br>

**Comment by msprijatelj** [comment] 2021-12-11 06:26
Duplicate of #1777, refer to that issue for the workaround.  #1780 should have solved this for any future imports, but if they persist for more than a week or two I'll reopen #1777.

**Closed by msprijatelj** 2021-12-11 06:26 UTC
Labels: bug, triage, app
