### ISSUE TITLE
[BUG] Visual Theme Bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#815] opened 2020-04-28 09:39 UTC
<strong>Submitted At: </strong>4/28/2020 4:39:13
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
The theme of C/C always boots up looking like GMS Red, even when set to MSMC Dark before closing. When observed in the options menu, Theme is set to MSMC even when the appearance is GMS.
<strong>To Reproduce: </strong>
Set Theme to MSMC Dark, close C/C, and reopen. Open options to observe that it's still set to MSMC Dark.
<strong>Expected behavior: </strong>
I expected it to stay in the visual theme I set it to.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
ActualWizard#0434
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-04-29 17:18
dupe of #761

**Closed by jarena3** 2020-04-29 17:18 UTC
Labels: bug, duplicate, executable
