### ISSUE TITLE
Feature Request: This would be extremely helpfull for my players to have their character sheets on their phones

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#109] opened 2019-04-24 10:38 UTC
<strong>Submitted At: </strong>4/24/2019 5:38:21
<strong>Feature: </strong>Android/Ios
<strong>Details: </strong>This would be extremely helpfull for my players to have their character sheets on their phones

**Comment by aritsune** [comment] 2019-07-13 21:03
Dupe of #300

**Closed by aritsune** 2019-07-13 21:03 UTC
Labels: enhancement
