### ISSUE TITLE
[BUG] Custom names for systems can't be edited.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1519] opened 2021-07-07 16:12 UTC
<strong>Submitted At: </strong> 7/7/2021 11:12:14<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> It is giving me the ERROR:   setting getter-only property "Name"<br><br><strong>Reproduction Steps:<br> </strong> Make a custom name for a system under NPC's.<br><br><strong>Expected Result:<br> </strong> Change of name<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
Et@https://compcon.app/app.bundle.js:22:7480
save@https://compcon.app/app.bundle.js:233:26012
save@https://compcon.app/app.bundle.js:233:25450
Ut@https://compcon.app/app.bundle.js:22:11252
n@https://compcon.app/app.bundle.js:22:12996
Ut@https://compcon.app/app.bundle.js:22:11252
t.prototype.$emit@https://compcon.app/app.bundle.js:22:34199
s</e.prototype.save@https://compcon.app/app.bundle.js:343:887748
s</e.prototype.confirm@https://compcon.app/app.bundle.js:343:887457
keyup@https://compcon.app/app.bundle.js:343:886692
Ut@https://compcon.app/app.bundle.js:22:11252
n@https://compcon.app/app.bundle.js:22:12996
yi/o._wrapper@https://compcon.app/app.bundle.js:22:44399
```<br>

**Comment by jarena3** [comment] 2021-07-16 18:08
Duplicate of #1506

**Closed by jarena3** 2021-07-16 18:08 UTC
Labels: app, bug, triage
