### ISSUE TITLE
[BUG] Pilot Roster Not Working

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1787] opened 2021-12-11 20:46 UTC
<strong>Submitted At: </strong> 12/11/2021 14:46:31<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> After the most recent update, the pilot roster is unnaccessable due to: Cannot read properties of undefined (reading 'length').<br><br><strong>Reproduction Steps:<br> </strong> AFter the update it just occurs whenever I try and open the pilot roster.<br><br><strong>Expected Result:<br> </strong> The Pilot roster to open.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)```<br>

**Comment by msprijatelj** [comment] 2021-12-12 03:26
Duplicate of #1785

**Closed by msprijatelj** 2021-12-12 03:26 UTC
Labels: bug, triage, app
