### ISSUE TITLE
[BUG] Self heat tag in profiled weapon inflicts stress

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1383] opened 2021-04-13 07:35 UTC
<strong>Submitted At: </strong>4/13/2021 2:35:14
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Barraging with a weapon with a self heat tag on a profile inflicts stress on the users frame, in addition to the heat.
<strong>To Reproduce: </strong>
Install an lcp with a profiled weapon which inflicts self heat on one of the modes. E.g. the Worden's cannon from Suldan.
Create a frame with the weapon equipped. Go to active mode. Select the full action to barrage with the intended weapon. Resolve the rolls as required and a pop-up reporting reactor stress will appear.
<strong>Expected behavior: </strong>
Heat to be increased but not stress dealt
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-04-13 16:24
duplicate of #1365

**Closed by jarena3** 2021-04-13 16:24 UTC
Labels: bug, triage
