### ISSUE TITLE
[BUG] Ekidnu Plasma Talons Selectable from the weapons menu at all times

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1553] opened 2021-07-27 16:00 UTC
<strong>Submitted At: </strong> 7/27/2021 11:00:05<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The HA Plasma talons (Ekidnu Integrated system) Seem to be selectable at all times from the weapons menu<br><br><strong>Reproduction Steps:<br> </strong> Seemed to show up after having a Pilot with the Ekidnu in the roster<br><br><strong>Expected Result:<br> </strong> These probably shouldnt be selectable as an Aux weapon as they are an integrated system, and there aren't any Licenses that unlock the weapon<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment] 2021-07-28 19:41
Duplicate of #1547

**Closed by jarena3** 2021-07-28 19:41 UTC
Labels: app, bug, triage
