### ISSUE TITLE
Feature Request: Integrated compendium tables frozen/floating header row

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#249] opened 2019-06-16 19:27 UTC
<strong>Submitted At: </strong>6/16/2019 14:27:46
<strong>Feature: </strong>Integrated compendium tables frozen/floating header row
<strong>Details: </strong>When viewing longer tables in the Compendium, particularly the large Frames view full of frame stats, it would help if the row of headers could be floated/frozen to follow the viewport when scrolling, so that there's no need to scroll back up each time.
<strong>Contact: </strong>@Qwertronix#4443

**Comment by aritsune** [comment] 2020-01-02 22:55
Duplicate of #93

**Closed by aritsune** 2020-01-02 22:55 UTC
Labels: Compendium, enhancement
