### ISSUE TITLE
[BUG] Cannot see any of my pilots - reloading used to just show an empty pilot page now it just shows nothing 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1784] opened 2021-12-11 04:48 UTC
<strong>Submitted At: </strong> 12/10/2021 22:48:09<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Clicking on Pilot Roster shows nothing. Gives the error about  properties of undefined 'length'. <br><br><strong>Reproduction Steps:<br> </strong> Click on Pilot Roster, be given the 'Cannot read properties of undefined (Reading 'Length'). Reload, observe that nothing changes. Receive the same error. <br><br><strong>Expected Result:<br> </strong> I expected to see my list of pilots<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)```<br>

**Comment by msprijatelj** [comment] 2021-12-11 06:26
Duplicate of #1777, refer to that issue for the workaround.  #1780 should have solved this for any future imports, but if they persist for more than a week or two I'll reopen #1777.

**Closed by msprijatelj** 2021-12-11 06:26 UTC
Labels: bug, triage, app
