### ISSUE TITLE
[BUG] Website is not updating to 2.3.8 and is stuck on 2.2.35

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2026] opened 2022-06-01 21:39 UTC
<strong>Submitted At: </strong> 6/1/2022 16:39:25<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Website is openning only old version and refuses to update it, even by "check for updates" button, on Firefox everything is ok<br><br><strong>Reproduction Steps:<br> </strong> Launch website on Opera<br><br><strong>Expected Result:<br> </strong> Seeing Comp con 2.3.8<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-06-01 23:14
Duplicate of #1993

**Closed by msprijatelj** 2022-06-01 23:14 UTC
Labels: bug, triage, app
