### ISSUE TITLE
[BUG] UI for Barrage Issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1403] opened 2021-04-26 00:51 UTC
<strong>Submitted At: </strong>4/25/2021 19:51:07
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When placing a barrage action while having three possible attacks, and when having the Chrome window moved to the side of the monitor (like when using one side for compcon and the for tabletop simulator), the second barrage attack prompt is cut off on the bottom of the screen. Clicking outside of the window will resolve the action and compcon considers the action completed even though the roll did not occur.
<strong>To Reproduce: </strong>
use the neslon frame with warpike and nexus in the main/aux slot and shotgun in the flex slot. When compcon is is combat mode, move the window to one side of the monitor, scroll down and barrage with main/aux first, then flex. Resolve the first two weapons and attempt to resolve the shotgun.
<strong>Expected behavior: </strong>
I see the window to roll a hit and roll damage for the shotgun.
<strong>Additional context: </strong>
https://imgur.com/x761zcf the bottom right shows the window being cut off.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-06-04 20:00
Duplicate of #1391

**Closed by jarena3** 2021-06-04 20:00 UTC
Labels: bug, triage
