### ISSUE TITLE
[BUG] Blast Damage on Multiple Targets

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2485] opened 2024-07-22 19:00 UTC
<strong>Submitted At: </strong> 7/22/2024 14:00:30<br><br><strong>Issue: </strong><br> In active mode when skirmishing with a Howitzer, I saw that I could only make one attack roll. I expected to see an option to make another attack roll for an additional target with the same attack, following the rules for Blast in Lancer, "A separate attack roll is made for each target".<br><br><strong>Massif Reference: </strong> Lancer Core Book page 64<br>

**Comment by msprijatelj** [comment] 2024-07-22 21:29
Duplicate of #1628

**Closed by msprijatelj** 2024-07-22 21:29 UTC
Labels: bug, triage, rules
