### ISSUE TITLE
[BUG] NPC Classes - HP/Armor Sort Broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1524] opened 2021-07-09 22:01 UTC
<strong>Submitted At: </strong> 7/9/2021 17:01:04<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Clicking sort for 'HP' or 'Armor' does nothing. The arrow appears, but that's it.<br><br><strong>Reproduction Steps:<br> </strong> Open 'NPC Classes'. Click 'HP' at the top of the spread sheet. Do it again. Do the same for Armor. No changes.<br><br><strong>Expected Result:<br> </strong> Spead Sheet Sort to work like it does on other columns<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment] 2021-07-16 18:07
Duplicate of #840

**Closed by jarena3** 2021-07-16 18:07 UTC
Labels: app, bug, triage
