### ISSUE TITLE
[BUG] Default Terminal Theme

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1491] opened 2021-06-20 11:27 UTC
<strong>Submitted At: </strong> 6/20/2021 6:27:23<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Whenever COMP/CON is reloaded or opened in a new tab, it used to keep the terminal theme that I set from last time I was on the site, HORUS in my case. Now, when I have made an account and am logged in, it instead resets back to the default red theme whenever the page is reloaded or opened in a new tab instead.

This is only the case while I am logged in. When I log out, it works as it used to, keeping the theme I had set last time I was on the site, like I want it to.<br><br><strong>Reproduction Steps:<br> </strong> As mentioned above, it does not save the terminal theme when logged in, only when logged out, so I suppose that would be considered how to reproduce the issue.<br><br><strong>Expected Result:<br> </strong> I expected it to keep the HORUS theme that I had selected like it always had been before I made an account and logged into the site.<br><br><strong>Additional Context:<br> </strong> Unsure<br><br><br><strong>Stack Trace: </strong> There is nothing in the error log<br>

**Comment by jarena3** [comment] 2021-06-28 20:37
duplicate of #1450

**Closed by jarena3** 2021-06-28 20:37 UTC
Labels: app, bug, triage
