### ISSUE TITLE
[BUG] Mysterious Regenerating Core Power

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#823] opened 2020-04-29 05:11 UTC
<strong>Submitted At: </strong>4/29/2020 0:11:43
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When returning to COMP/CON's active play mode, an exhausted core power will show back up as available even though other stats are tracked properly.
<strong>To Reproduce: </strong>
Enter active mode with a pilot, mark 1 damage, 1 heat, and exhaust the core power. Go back to the home screen, then refresh C/C. When going back into active mode for that pilot, the damage and heat will still be marked, but the core power will be back.
<strong>Expected behavior: </strong>
Should remain exhausted.
<strong>Additional context: </strong>
Tested both with my main Everest pilot and an LL2 Swallowtail I have; same results both times.
<strong>Contact Info: </strong>
Nasajin#1006
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-04-29 14:44
dupe of #790

**Closed by jarena3** 2020-04-29 14:44 UTC
Labels: bug, duplicate
