### ISSUE TITLE
[BUG] setting getter-only property "Name"

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1525] opened 2021-07-11 00:51 UTC
<strong>Submitted At: </strong> 7/10/2021 19:50:57<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> whenever i attempt to edit (reset OR change) the item name field of a piece of mech gear, an error appears reading "ERROR: setting getter-only property 'Name'" and the name is not changed. when i attempt to edit the description field, no error message appears but the description is not changed.<br><br><strong>Reproduction Steps:<br> </strong> hard to say what caused it; it happened in the middle of me creating several NPCs and now affects every piece of mech gear on all of my NPCs as far as i can tell, including both newly created/imported ones and old pre-existing ones. it started immediately after i deleted a re-named trait from a Suldan NPC (Slipwave, which had been renamed to "Notional Drift"). when i attempted to return the feature to the NPC and rename it, it was broken as described above. it has not gone away, even after clearing website cache and losing about half an hour's worth of work in the process. it has even bafflingly persisted into an incognito window where i did not log into my cloud account and i only installed the core lancer NPC content pack.<br><br><strong>Expected Result:<br> </strong> i expected to be able to set the names and descriptions on my NPC mechs.<br><br><strong>Additional Context:<br> </strong> i have many content packs installed: all of the official lancer content packs + the field guide to suldan & incomplete KTB guide content packs. some of these (wallflower + long rim) were outdated at the time the bug appeared; i have since updated them and it has not gone away.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
Et@https://compcon.app/app.bundle.js:22:7480
save@https://compcon.app/app.bundle.js:233:26012
save@https://compcon.app/app.bundle.js:233:25450
Ut@https://compcon.app/app.bundle.js:22:11252
n@https://compcon.app/app.bundle.js:22:12996
Ut@https://compcon.app/app.bundle.js:22:11252
t.prototype.$emit@https://compcon.app/app.bundle.js:22:34199
s</e.prototype.save@https://compcon.app/app.bundle.js:343:887748
s</e.prototype.confirm@https://compcon.app/app.bundle.js:343:887457
click@https://compcon.app/app.bundle.js:343:887200
Ut@https://compcon.app/app.bundle.js:22:11252
n@https://compcon.app/app.bundle.js:22:12996
Ut@https://compcon.app/app.bundle.js:22:11252
t.prototype.$emit@https://compcon.app/app.bundle.js:22:34199
click@https://compcon.app/app.bundle.js:191:265125
Ut@https://compcon.app/app.bundle.js:22:11252
n@https://compcon.app/app.bundle.js:22:12996
yi/o._wrapper@https://compcon.app/app.bundle.js:22:44399
```<br>

**Comment by jarena3** [comment] 2021-07-16 18:06
Duplicate of #1519

**Closed by jarena3** 2021-07-16 18:06 UTC
Labels: app, bug, triage
