### ISSUE TITLE
[BUG] When leveling up, active Talents are not shown. Clicking name in left panel shows error message "ERROR:   Container element ".v-dialog--active" not found"

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1368] opened 2021-04-06 01:55 UTC
<strong>Submitted At: </strong>4/5/2021 20:55:38
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When leveling up, active Talents are not shown. Clicking name in left panel shows error message "ERROR:   Container element ".v-dialog--active" not found"
<strong>To Reproduce: </strong>
Begin level up. Click name of active Talent in left panel.
<strong>Expected behavior: </strong>
Active Talents shown
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
```
Vue error at [e]
Error: Container element ".v-dialog--active" not found.
    at https://compcon.app/app.bundle.js:196:637701
    at Object.O (https://compcon.app/app.bundle.js:196:637848)
    at click (https://compcon.app/app.bundle.js:210:985065)
    at Ut (https://compcon.app/app.bundle.js:37:11252)
    at HTMLButtonElement.n (https://compcon.app/app.bundle.js:37:12996)
    at HTMLButtonElement.r._wrapper (https://compcon.app/app.bundle.js:37:44399)```

**Comment by jarena3** [comment] 2021-04-08 16:43
Duplicate of #1363

**Closed by jarena3** 2021-04-08 16:43 UTC
Labels: bug, triage
