### ISSUE TITLE
Bug Report: Encounters cannot be deleted

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#297] opened 2019-07-13 15:42 UTC
<strong>Submitted At: </strong>7/13/2019 10:42:57
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Encounters cannot be deleted
<strong>Reproduction Steps: </strong>Create an active encounter, then attempt to delete it.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment] 2019-07-13 20:29
Duplicate of #292

**Closed by aritsune** 2019-07-13 20:29 UTC
Labels: bug
