### ISSUE TITLE
[BUG] Login issues on mobile

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1804] opened 2021-12-23 04:34 UTC
<strong>Submitted At: </strong> 12/22/2021 22:34:00<br><br><strong>Browser: </strong> Safari<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I can’t login the login buttons there but when I hit it it gives me an error message <br><br><strong>Reproduction Steps:<br> </strong> You hit the login button on mobile on safari also I’m using a apply iPhone 6 with really outdated safari<br><br><strong>Expected Result:<br> </strong> I’m able to login to compcon <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2021-12-23 14:43
More information (iOS version, Safari version, error code) would be helpful in reproducing this error, but I don’t know if more will be forthcoming.

**Comment by jarena3** [comment] 2022-04-15 16:31
this worked for me when I tested it on an iPhone 8; I think it might be due to the safari version? Going to close this unless it pops up again

**Closed by jarena3** 2022-04-15 16:31 UTC
Labels: bug, triage, app, mobile
