### ISSUE TITLE
Feature Request: Lock the Table Header Row

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#404] opened 2019-11-01 11:40 UTC
<strong>Submitted At: </strong>11/1/2019 6:40:24
<strong>Feature: </strong>Lock the Table Header Row
<strong>Details: </strong>When I scroll down in a table with many rows, I want to always see the column headers. Basically, make only the table contents scroll and not the table headers.

Thanks!
<strong>Contact: </strong>

**Comment by aritsune** [comment] 2020-01-03 16:36
Duplicate of #93

**Closed by aritsune** 2020-01-03 16:36 UTC
Labels: enhancement
