### ISSUE TITLE
[BUG] Pilot Roster title text cut off

### ISSUE THREAD

**Issue by pkarjala** [massif-press/compcon#2171] opened 2023-01-10 20:52 UTC
**Describe the bug**
On the Pilot Roster main page, the header text "Pilot Roster" is cut off at the top of the screen.  Appears on both Desktop and Smartphone in Portrait mode.

**To Reproduce**
1. Go to [https://compcon.app/#/pilot_management](https://compcon.app/#/pilot_management)
2. See issue with text being cut off.

**Expected behavior**
Text should not be cut off.  

**Screenshots**
![pilot_roster_bug_text](https://user-images.githubusercontent.com/5232936/211659278-da88cc87-cae3-42b5-b712-e0f6b7f077ac.jpg)

**Desktop:**
 - OS: Windows 10 Pro 22H2
 - Browser: Firefox
 - Version:  108.0.2

**Smartphone:**
 - Device: iPhone Xr
 - OS: iOS 16.2
 - Browser: Firefox (webkit)
 - Version: 108.1

**Additional context**
Looks like a simple padding / margin fix should resolve the issue.

**Comment by msprijatelj** [comment] 2023-01-11 01:26
This is a weird one because all the weird styling issues (this title cutoff, weird look on the LL editor’s number drop-down) don’t appear when building and running locally. I believe I mentioned to @jarena3 that this may have been a weird reversion of Vuetify on Netlify’s end, but I believe forcing a rebuild of Netlify’s NodeJS packages didn’t fix the issue? Maybe it’s worth another try?

**Comment by msprijatelj** [comment] 2024-05-18 13:30
Duplicate of #2464

**Closed by msprijatelj** 2024-05-18 13:30 UTC
