### ISSUE TITLE
[BUG] pilot registering issues

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2043] opened 2022-06-26 04:51 UTC
<strong>Submitted At: </strong> 6/25/2022 23:51:00<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> every time i sent my vault code and someone imports my character, on my end the character changes to showing as 'This pilot is registered to another user.' <br><br><strong>Reproduction Steps:<br> </strong> I have made several copies of the character now, and when i made the duplicate copy it shows that its MY character, once i share the new vault code, the message that the pilot is registered to another user appears.<br><br><strong>Expected Result:<br> </strong> Please fix this issue so that i can share my character without the registration changing to the person who imports the code.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-06-26 04:54
Given the use of Vault Code in the description, it sounds like the user is stuck on a previous version of compcon.  Treating this as a duplicate of #1993.

**Closed by msprijatelj** 2022-06-26 04:54 UTC
Labels: bug, triage, app
