### ISSUE TITLE
[BUG] Unable to scroll far enough to confirm rolls

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1454] opened 2021-06-04 14:21 UTC
<strong>Submitted At: </strong>6/4/2021 9:21:07
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When rolling damage for certain weapons the confirm button is hidden beneath the browser. And when you scroll down the box follows denying access to it
<strong>To Reproduce: </strong>
Choose a barrage action or skirmish on a weapon, roll for attack, roll for damage, button is out of reach.
<strong>Expected behavior: </strong>
You scroll down and click the button.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-06-04 16:14
duplicate of #1402

**Closed by jarena3** 2021-06-04 16:14 UTC
Labels: bug, triage
