### ISSUE TITLE
[BUG] Add a save button

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2149] opened 2022-10-11 12:59 UTC
<strong>Submitted At: </strong> 10/11/2022 7:59:54<br><br><strong>Browser: </strong> Google on my iPhone<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I’ve changed my pilot gear and renamed my mechs but the changes always get changed back. Add a save button so my profile can be updated so I don’t have to keep constantly changing it back to what I want it to be. <br><br><strong>Reproduction Steps:<br> </strong> I don’t know how to reproduce the issue. Clearly the website is not updating after I put in the new information and then reverts back to its last remembered save state. Being able to manually force the page to update the information might work. <br><br><strong>Expected Result:<br> </strong> I expect when I input information it gets saved the way I put it in and not revert to old information. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by AmbushXXVI** [comment] 2022-11-01 14:33
Came here to see if this was already suggested. Unfortunately, whether it's the state detection, cloud functionality, or something else, it seems that none of the syncing is working as intended. In an effort to see if it was related to multiple tabs, I've been using only a single tab on one platform, and even that is failing to maintain the proper state. 

Potentially, this could be made into an option, so that if a player is having issues they could choose to stay in a manual save state?

**Comment by jarena3** [comment] 2023-04-27 16:53
Should be resolved in 2.3.11, collected in ticket #2222

**Closed by jarena3** 2023-04-27 16:53 UTC
Labels: bug, triage, app
