### ISSUE TITLE
[BUG] Formatting

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#746] opened 2020-03-30 04:30 UTC
<strong>Submitted At: </strong>3/29/2020 23:30:02
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The Rank 2 Blackthumb talent (Rodeo) has Field Repair and Rig Vents on the same line without bullet point.
<strong>To Reproduce: </strong>
Open the compendium and look at the talent Blackthumb Rank 2.
<strong>Expected behavior: </strong>
The Rig Vents action to be on a newline with a bullet point.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-03-30 13:17
Duplicate of #722

**Closed by jarena3** 2020-03-30 13:17 UTC
Labels: duplicate
