### ISSUE TITLE
[BUG] Double profiles

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1885] opened 2022-03-24 06:47 UTC
<strong>Submitted At: </strong> 3/24/2022 1:47:36<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I created a profile on my computer and then when I went to sign in with it on my phone it didn’t exist so I pressed create and now I have two profiles with the same email and password <br><br><strong>Reproduction Steps:<br> </strong> Create profile on pc, try and logon on apple phone and get error saying user doesn’t exist, so you press create and now have two profiles that aren’t the same but should be .<br><br><strong>Expected Result:<br> </strong> To be able to logon and see my pilot so I could alter thing on the go<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-03-24 11:50
Duplicate of #1850

**Closed by msprijatelj** 2022-03-24 11:50 UTC
Labels: bug, triage, app
