### ISSUE TITLE
[BUG] Enkidu Plasma Talons Available to All

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1556] opened 2021-07-29 05:14 UTC
<strong>Submitted At: </strong> 7/29/2021 0:14:24<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> The Enkidu's Plasma Talons show up as an available weapon to all pilots and shows up in the weapons list in the compendium, even though it shouldn't, as it is an integrated weapon unique to the enkidu.<br><br><strong>Correct Text/Data: </strong><br> This may be due to an improper "source:HA" tag in the plasma talon's profile in the lcp. I've checked the Caliban's integrated weapon in the long rim lcp, and that seems to be the only major difference between the two that could cause this, but I'm not familiar with how lcps work entirely.<br>

**Comment by lenaleciel** [comment] 2021-07-29 05:16
Duplicate of #1547

**Closed** 2021-07-29 15:38 UTC
Labels: bug, data, triage
