### ISSUE TITLE
[BUG] Skill Point reserve

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1600] opened 2021-08-06 21:08 UTC
<strong>Submitted At: </strong>8/6/2021 16:08:23
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When adding a skill point reserve to a license level 0 character, it adds the skill points but does not allow them to be spent (issue not present in higher level characters) additionally when adding skill point reserve to any level character it grants 2 skill points instead of 1 (allowing a +2 trigger to jump to +6) 
<strong>To Reproduce: </strong>
Enter character's narrative profile and add skill point reserve.
<strong>Expected behavior: </strong>
Will grant 2 skill points instead of 1 and if character is license level 0 will not be able to spend skill points
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
266331477380169728
<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment] 2021-08-06 21:26
Duplicate of #1589

**Closed** 2021-08-09 18:50 UTC
Labels: bug, triage
