### ISSUE TITLE
[BUG] Improved Armament replacing Plasma Talons

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1902] opened 2022-04-12 18:55 UTC
<strong>Submitted At: </strong> 4/12/2022 13:55:37<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Laptop<br><br><strong>Issue Description: </strong><br> When applying the Improved Armament GMS Corebonus to my character, the Flex Mount granted by the bonus replaces the Integrated Mount for the Plasma Talons on my Enkidu rather than augmenting it<br><br><strong>Reproduction Steps:<br> </strong> Step 1, Have an Enkidu in your hangar, Step 2, apply Improved Armament Core Bonus to Character, Step 3, scratch head in confusion as your primary gimmick for your mech disappears<br><br><strong>Expected Result:<br> </strong> I expected to get a Fourth Mount, not to have it be replaced<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-04-12 19:01
I am seeing that on Wallflower Version 1.0.8, Plasma Talons isn't appearing as an integrated weapon at all, regardless of Core Bonus.

**Comment by jarena3** [comment] 2022-04-12 20:28
Should be resolved in 2.3.0c, will wait to close though

**Comment by msprijatelj** [comment] 2022-04-12 20:50
With 2.3.0c, I can confirm that Talent-granted integrated mounts are back (though some, like the Fuel Rod Gun, are available earlier than intended ((Rank 2 instead of Rank 3)) ), but no frame-granted integrated mounts are currently visible (Going off a Raleigh and an Enkidu)

**Comment by jarena3** [comment] 2022-04-12 23:31
Pretty sure this one has been knocked out as of 3.2.1. Sure enough to close the ticket, at least

**Closed by jarena3** 2022-04-12 23:31 UTC
Labels: bug, app
