### ISSUE TITLE
[BUG] Unable to update compcon

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1996] opened 2022-05-06 12:05 UTC
<strong>Submitted At: </strong> 5/6/2022 7:05:36<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> My compcon is stuck on version 2.2.35 instead of 2.2.7a. It will not update, even when I click the update and reload button. Other solutions such as restarting my computer doesn't work.<br><br><strong>Reproduction Steps:<br> </strong> I have no idea. 
1. Roll back to 2.2.35
2. Attempt to update
3. Fail.<br><br><strong>Expected Result:<br> </strong> I expect it to update my game.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-05-06 12:27
Duplicate of #1993. Please check the Troubleshooting FAQ in the Wiki for a workaround.

**Closed by msprijatelj** 2022-05-06 12:27 UTC
Labels: bug, triage, app
