### ISSUE TITLE
[BUG] e.pilotIDs is undefined

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1794] opened 2021-12-13 03:48 UTC
<strong>Submitted At: </strong> 12/12/2021 21:48:47<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Won't load pilot roster database<br><br><strong>Reproduction Steps:<br> </strong> Currently signed in, and click on pilot roster button<br><br><strong>Expected Result:<br> </strong> Expected to be taken to pilot roster and mech hangar<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2021-12-14 00:26
Duplicate of #1785

**Closed by msprijatelj** 2021-12-14 00:26 UTC
Labels: bug, triage, app
