### ISSUE TITLE
Bug Report: Mount Modification Conflicts

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#435] opened 2019-12-19 05:05 UTC
<strong>Submitted At: </strong>12/18/2019 23:05:50
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Mount Modification Conflicts
<strong>Reproduction Steps: </strong>Description: Mount Retrofitting does not correctly apply to mechs that have additional mounts, created by either Integrated Weapons or Improved Armaments.

Case 1: Create a pilot who has Mount Retrofitting and Integrated Weapons, create an Everest. Attempt to apply Mount Retrofitting to the Flex mount on the Everest. The retrofit applies itself to the Main mount. If you attempt to apply it to the Main mount, then it applies to the heavy. Attempting to apply it to the heavy mount appears to push it out of the array, as it doesn't appear as an option on any other mount. Removing Integrated Weapons from the pilot causes the retrofit to apply and display itself correctly.

Case 2: Create a pilot who has Mount Retrofitting and Integrated Weapons, create a Nelson. Attempt to apply Mount Retrofitting to the Flex Mount on the Nelson. Similar results to the above.

Case  3: Create a pilot who has Mount Retrofitting, Integrated Weapons, and Improved Armament and create a Nelson. Attempting to apply Mount Retrofitting to either Flex mount appears to make it apply to the Main/Aux mount.

Case 4: Create a pilot who has Mount Retrofitting and Improved Armament, and create a Saladin. Attempt to apply Mount Retrofitting to the first flex mount. It appears to apply to the second. Remove the retrofit from the second mount, and attempt to apply it to the second mount. The option to remove/apply the retrofitting disappears completely.

Case 5: Create a pilot who has Mount Retrofitting and Improved Armament, and create a Nelson. Attempting to apply the retrofit creates a similar issue to case 3, but the retrofit appears to "correctly" install itself on the mount beneath the desired mount.

Additional Testing: Auto-Stabilizing Hardpoints and Burnout Insulation both work properly, regardless of the presence of additional mounts, each other, or retrofitted mounts. (Tested on Everest, Nelson, and Saladin)

Theory: Mount Retrofitting does not correctly adjust which mount it is trying to modify when there are additional mounts present on a mech, because the Mount ID/Order-in-the-Array/however-compcon-identifies-which-mount-is-which-in-a-loadout changes.

Proposed Bandaid 1: Add integrated/additional mounts after the "standard" mounts on loadout creation. This will be kind of ugly.

Proposed Bandaid 2: Move Improved Armament and Integrated Weapon mounts to fixed positions in the list of mounts, but only show up if the pilot has the relevant core bonus. This will likely create problems with homebrew frames/core bonuses!
<strong>Contact Info: </strong>wales grey#6842

**Comment by walesgrey** [comment] 2019-12-29 21:48
Likely the same issue as [this similar bug](https://github.com/massif-press/compcon/issues/403).

**Comment by aritsune** [comment] 2020-01-02 00:11
Went over every case in v2 and couldn't reproduce any of them, so I'm guessing beef fixed this weirdness. Closing.

**Closed by aritsune** 2020-01-02 00:11 UTC
Labels: bug
