### ISSUE TITLE
[BUG] Broken NPC Tags

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#685] opened 2020-03-07 16:09 UTC
<strong>Submitted At: </strong>3/7/2020 10:09:27
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
All NPC tags are displaying either no information or just their tags (protocol, reaction, etc.). Comp/Con v9016843, NPC data 1.0.3.
<strong>To Reproduce: </strong>
Load NPC data, go to apply a tag, click on any of their features.
<strong>Expected behavior: </strong>
To see a description of the feature.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by Eranziel** [comment] 2020-03-08 18:37
Duplicate of #682

**Closed by Eranziel** 2020-03-08 18:37 UTC
Labels: bug, duplicate
