### ISSUE TITLE
[BUG] NPCs cannot sort by stats

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1004] opened 2020-07-22 18:46 UTC
<strong>Submitted At: </strong>7/22/2020 13:46:31
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
You click on the stat (e.g. armor) and compcon doesn't sort by it (despite showing the graphic that its sorting by it)
<strong>To Reproduce: </strong>
attempt to sort by stats in the npc list
<strong>Expected behavior: </strong>
that it sorts by stat, lowest to highest/vice versa
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Fwuffy (Luna)#1371
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-02-12 19:11
duplicate of #840

**Closed by jarena3** 2021-02-12 19:11 UTC
Labels: bug, duplicate, triage
