### ISSUE TITLE
[BUG] Can't import pilot image

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#839] opened 2020-05-08 23:42 UTC
<strong>Submitted At: </strong>5/8/2020 18:42:25
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Error on trying to load pilot image.
<strong>To Reproduce: </strong>
When pressing the "ADD IMAGE TO COLLECTION" button I get the error popup: "ERROR:
 
The "path" argument must be of type string. Received type undefined".  The file select window still opens and I can select but it does not import.
<strong>Expected behavior: </strong>
Load image.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
```
Vue error at [cc-btn]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.parse (path.js:819:5)
    at file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:94:66203
    at file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:16:2057
    at Object.next (file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:16:2162)
    at file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:16:1099
    at new Promise (<anonymous>)
    at s (file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:16:873)
    at A (file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:94:66076)
    at a.<anonymous> (file:///C:/Users/aarn/AppData/Local/Temp/1b92YQcYXKcUQHfyJdfr0WZ5jRI/resources/app.asar/app/app.bundle.js:109:746373)```

**Comment by jarena3** [comment] 2020-05-22 20:09
Dupe of #813

**Closed by jarena3** 2020-05-22 20:09 UTC
Labels: bug, duplicate, executable
