### ISSUE TITLE
[BUG] Lingering Remote Resources

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2147] opened 2022-10-07 01:50 UTC
<strong>Submitted At: </strong> 10/6/2022 20:50:19<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Smart Sync automatically restores deleted Remote Resources no matter what data is overwritten after their deletion<br><br><strong>Reproduction Steps:<br> </strong> 1) Login and turn on Smart Sync
2) Add a Remote Resource
3) Delete the Remote Resource
4) Close and open Comp/Con
5) The Remote Resource should be back<br><br><strong>Expected Result:<br> </strong> Expected Remote Resource to stay deleted/have an option to permanently delete (as none exists in the cloud menu at the moment)<br><br><strong>Additional Context:<br> </strong> uBlock Origin adblocker used<br><br><br><strong>Stack Trace: </strong> N/A<br>

**Comment by msprijatelj** [comment] 2022-10-07 03:13
I can reproduce this issue (without uBlock Origin or other extensions interfering). Deleting the remote pilot from the Pilot Roster doesn't seem to affect the Sync menu, and the remote pilot seems to return after a refresh or two.

Workaround to delete all remote resources, since they only exist in the local browser data:
1. Save a backup using "Create Data Backup"
2. Logout of CompCon
3. Navigate to Options, click "Delete All User Data" (this will clear the Local Data only since you're logged out)
4. Log back in, pull from cloud

**Comment by jarena3** [comment] 2023-04-27 16:53
Should be resolved in 2.3.11, collected in ticket #2222

**Closed by jarena3** 2023-04-27 16:53 UTC
Labels: bug, app
