### ISSUE TITLE
[BUG] Prototype Weapon Wrong Tags

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#800] opened 2020-04-22 07:16 UTC
<strong>Submitted At: </strong>4/22/2020 2:16:27
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I made a loadout for a mech that included the Engineering 1 weapon, but then upgraded to Engineering 3, and the prototype weapon doesn't seem to update to reflect the better stats, even after a full repair. Making a new loadout does put in the correct stats.
<strong>To Reproduce: </strong>
See bug above.
<strong>Expected behavior: </strong>
Existing loadouts should reflect the current state of the Engineer talent, not what it was when the loadout was created.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-04-27 19:01
duplicate of #763

**Closed by jarena3** 2020-04-27 19:01 UTC
Labels: bug, duplicate
