### ISSUE TITLE
Emperor systems become greyed out even when they should be usable again

### ISSUE THREAD

**Issue by MudFishs** [massif-press/compcon#2086] opened 2022-08-07 23:07 UTC
**Describe the bug**
After using a system like The Imperial Eye or Dominion's Breadth, they become greyed out and cannot be used again even on subsequent turns where they should be usable.

**To Reproduce**
1. Activate the system
2. Take turn as normal
3. End turn
4. Start next round
5. Error should be visible now

**Expected behavior**
System should be usable as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/110792206/183314635-747137b6-6c1e-4786-a9e0-9edf8dba283e.png)
System is not marked as used, and Dominion's Breadth above Imperial Eye is not used and displays as available

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Comp/Con 2.3.9a

**Comment by msprijatelj** [comment] 2022-08-08 02:04
Duplicate of #2005

**Closed by msprijatelj** 2022-08-08 02:04 UTC
