### ISSUE TITLE
[BUG] Desktop Comp/Con does not save theme.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#826] opened 2020-04-29 16:50 UTC
<strong>Submitted At: </strong>4/29/2020 11:50:58
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
When closing / restarting desktop version, the ui theme setting is not saved
<strong>To Reproduce: </strong>
User Options, change theme to Dark. Close and relaunch program, the theme will be back to default.
<strong>Expected behavior: </strong>
Theme should save between instances of the program.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-04-29 17:17
dupe of #815

**Closed by jarena3** 2020-04-29 17:17 UTC
Labels: bug, duplicate
