### ISSUE TITLE
[BUG] Typo in Trample Description for Cataphract

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1797] opened 2021-12-16 08:51 UTC
<strong>Submitted At: </strong> 12/16/2021 2:51:26<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> The Cataphract ignores engagement and can pass through – but not stop in – spaces occupied by other characters, dealing 3 kinetic damage to those characters.<br><br><strong>Correct Text/Data: </strong><br> The Cataphract ignores engagement and can pass
through – but not stop in – spaces occupied by other
characters, 1/turn dealing 2/3/4 kinetic damage to those characters.<br>

**Comment by msprijatelj** [comment] 2021-12-16 13:20
Duplicate of #1743

**Closed by msprijatelj** 2021-12-16 13:20 UTC
Labels: bug, triage, data
