### ISSUE TITLE
[BUG] Odd behavior with padding

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1972] opened 2022-04-23 16:28 UTC
<strong>Submitted At: </strong> 4/23/2022 11:27:59<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Inside the Active Mode, elements close to the top of a window seem to be cut off by toolbar or header, happens with the Pilot's callsign, and once inside combat, it happens on the information displayed for some actions as well<br><br><strong>Reproduction Steps:<br> </strong> Enter Active mode, this should display the Callsign already cut, then start a combat, bringing (for example) Barrage up will show the description being cut, and even after expanding, it remains the same. However, some actions like Boot Up, Dismount and Prepare are displaying correctly.<br><br><strong>Expected Result:<br> </strong> For the text on the actions to be legible for players to read<br><br><strong>Additional Context:<br> </strong> Screenshots: https://imgur.com/a/5UC0S5x<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2024-05-18 13:30
Duplicate of #2464

**Closed by msprijatelj** 2024-05-18 13:30 UTC
Labels: bug, triage, app
