### ISSUE TITLE
[BUG] Mobile Website use

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1770] opened 2021-11-12 04:16 UTC
<strong>Submitted At: </strong> 11/11/2021 22:16:53<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I created an account using my laptop but when I try to login on my phone it tells me that my account doesn't exist so I can't access any of the information.<br><br><strong>Reproduction Steps:<br> </strong> I've tried logging out and logging in multiple times but it still just says it doesn't exist on my phone but works without issue when logging in on my laptop.<br><br><strong>Expected Result:<br> </strong> That I'd be able to access it on my phone as easily as I can on my laptop.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2021-11-12 06:34
If the issue author is reading this, please double check that the email addresses on your phone has the same capitalization as the email used to login on the laptop. The account username is case-sensitive, and I know mobile devices sometimes auto-capitalize the username field.

**Comment by jarena3** [comment] 2021-11-23 19:21
duplicate of #1737

**Closed by jarena3** 2021-11-23 19:21 UTC
Labels: bug, triage, app
