### ISSUE TITLE
Bug Report: not quite sure if its a bug or a feature. you can take custom paint job multiple times.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#470] opened 2020-01-14 22:21 UTC
<strong>Submitted At: </strong>1/14/2020 16:21:58
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>not quite sure if its a bug or a feature. you can take custom paint job multiple times.
<strong>Reproduction Steps: </strong>if its a feature leave it be.
<strong>Contact Info: </strong>Tigg_kazzuma_MD#0001

**Comment by aritsune** [comment] 2020-01-14 23:10
duplicate of #473

**Closed by aritsune** 2020-01-14 23:10 UTC
Labels: bug
