### ISSUE TITLE
Bug Report: Comp/Con won't let me respec into 2 talents

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#475] opened 2020-01-14 23:01 UTC
<strong>Submitted At: </strong>1/14/2020 17:01:27
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Comp/Con won't let me respec into 2 talents
<strong>Reproduction Steps: </strong>Make a pilot. Edit their talents so you only have two. The program will say you need three. You don't. https://discordapp.com/channels/426286410496999425/568459736119509023/663579510708371468
<strong>Contact Info: </strong>Neverender

**Comment by aritsune** [comment] 2020-01-14 23:05
duplicate of #394

**Closed by aritsune** 2020-01-14 23:05 UTC
Labels: bug
