### ISSUE TITLE
[BUG] Error displaying Pilot Roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1789] opened 2021-12-12 00:46 UTC
<strong>Submitted At: </strong> 12/11/2021 18:46:17<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I updated the browser app and connected. After, when opening the pilot roster I received multiple errors.<br><br><strong>Reproduction Steps:<br> </strong> Update the browser app and connect.  Open the pilot roster.<br><br><strong>Expected Result:<br> </strong> Correct display and intractability found in pilot roster.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ERROR 3
```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)```
ERROR 2
```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at un.run (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:27494)
    at pn (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:25602)
    at Array.<anonymous> (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:12293)
    at Jt (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:11737)```
ERROR 1
```
Vue error at [e]
TypeError: t.profile.GetView is not a function
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:218063)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)
    at n (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:23166)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:52509```<br>

**Comment by msprijatelj** [comment] 2021-12-12 03:26
Duplicate of #1785

**Closed by msprijatelj** 2021-12-12 03:26 UTC
Labels: bug, triage, app
