### ISSUE TITLE
Bug Report: Miscalculated SP

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#376] opened 2019-09-13 22:38 UTC
<strong>Submitted At: </strong>9/13/2019 17:38:39
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Miscalculated SP
<strong>Reproduction Steps: </strong>I might be doing something wrong here, but I've noticed the SP cost of my modules on my monarch only adds to 5, but compcon is showing 0/6 SP remaining.
<strong>Contact Info: </strong>DaBawsch#6669

**Comment by aritsune** [comment] 2020-01-02 00:44
looks like a dupe of #393 which is probably fixed

**Closed by aritsune** 2020-01-02 00:44 UTC
Labels: bug
