### ISSUE TITLE
[BUG] Dominion's Breadth does not reset on next turn

### ISSUE THREAD

**Issue by kurama101** [massif-press/compcon#2152] opened 2022-10-16 14:51 UTC
**Describe the bug**
Dominion's Breadth quick tech action (Emperor L1) remains greyed out after use and does not appear in the quick tech dropdown, even on subsequent turns or if overcharge is activated. If overcharge is used it seems to grey out bolster too.

**To Reproduce**
1. Use Dominion's Breadth in combat
2. End turn
3. Try to use Dominion's Breadth on the next turn

**Expected behavior**
Overshields do not stack, but Dominion's Breadth can be used on multiple different targets and is not Limited so should be able to be used more than once.

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Firefox 105.0.3 (64-bit)
 - Version COMP/CON2.3.11

**Comment by msprijatelj** [comment] 2022-10-17 00:49
Duplicate of #2005

**Closed by msprijatelj** 2022-10-17 00:49 UTC
