### ISSUE TITLE
[BUG] Typing "hand" into NPC features locks up comp con

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1806] opened 2021-12-31 08:06 UTC
<strong>Submitted At: </strong> 12/31/2021 2:05:57<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> searching "hand" in the NPC features search bar locks up the app, no buttons work<br><br><strong>Reproduction Steps:<br> </strong> turned on "show all features" and Typed in "hand" into the search bar and it locks up, have to restart the web app for it to function.<br><br><strong>Expected Result:<br> </strong> To show all of the quires with "hand" in the name and not lock up<br><br><strong>Additional Context:<br> </strong> it also doesn't show anything with hand in the title <br><br><br><strong>Stack Trace: </strong> nothing in error log <br>

**Comment by msprijatelj** [comment] 2022-04-18 18:42
Assumed to be a duplicate of #1893

**Closed by msprijatelj** 2022-04-18 18:42 UTC
Labels: bug, triage, app

**Comment by msprijatelj** [comment] 2022-04-18 21:07
Also collecting in #1375
