### ISSUE TITLE
[BUG] Pilot manager fails to load

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1837] opened 2022-01-25 17:23 UTC
<strong>Submitted At: </strong> 1/25/2022 11:23:27<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When Pilot manager is selected, Error: Length cannot be defined message displays and fails to load<br><br><strong>Reproduction Steps:<br> </strong> click on pilot manager <br><br><strong>Expected Result:<br> </strong> Pilots be available <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-03-17 19:10
Duplicate of #1870

**Closed by msprijatelj** 2022-03-17 19:10 UTC
Labels: bug, triage, app
