### ISSUE TITLE
[BUG] NPC classes don't sort on their tabs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#969] opened 2020-07-11 23:47 UTC
<strong>Submitted At: </strong>7/11/2020 18:47:26
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
In the compendium, the NPC class table's tabs don't sort the NPCs when you select them.
<strong>To Reproduce: </strong>
Enter the Compendium with the base NPC and Wallflower beta test LCPs installed, then attempt to sort by armor, health, etc.
<strong>Expected behavior: </strong>
I would expect the table to reorganize the list according to increasing or decreasing value when using the tabs.
<strong>Additional context: </strong>
If y'all wanted to have filters for the NPCs too, that'd be cool, but that's a feature request ticket and not the purpose of this one.
<strong>Contact Info: </strong>
Izaak#7354
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2020-07-13 18:04
dupe of #840

**Closed by jarena3** 2020-07-13 18:04 UTC
Labels: bug, triage
