### ISSUE TITLE
Feature Request: An app for phones/ipads like Hero Lab.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#187] opened 2019-05-28 04:12 UTC
<strong>Submitted At: </strong>5/27/2019 23:12:16
<strong>Feature: </strong>COMP/CON app (IOS/Android)
<strong>Details: </strong>An app for phones/ipads like Hero Lab.
<strong>Contact: </strong>

**Comment by aritsune** [comment] 2019-07-13 21:03
Dupe of #300

**Closed by aritsune** 2019-07-13 21:03 UTC
Labels: enhancement
