### ISSUE TITLE
[BUG] Typo in "Bond of the Titan"

### ISSUE THREAD

**Issue by Magus7** [massif-press/compcon#2210] opened 2023-04-03 03:14 UTC
**Describe the bug**
The Bond of the Titan entry in the Compendium is missing the "I led from the front" minor ideal in the minor ideals list.

**Comment by msprijatelj** [comment] 2023-04-03 12:37
Duplicate of https://github.com/massif-press/ktb-data/issues/10

**Closed by msprijatelj** 2023-04-03 12:37 UTC
