### ISSUE TITLE
[BUG] Movement Tracking

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1156] opened 2021-01-08 03:04 UTC
<strong>Submitted At: </strong>1/7/2021 21:04:16
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Movement Tracker cannot go to zero without typing in a value
<strong>To Reproduce: </strong>
Just click on it?
<strong>Expected behavior: </strong>
Should be able to click off all movement without having to use the keyboard.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by Eranziel** [comment] 2021-01-08 14:24
Duplicate of #1130

**Closed by Eranziel** 2021-01-08 14:24 UTC
Labels: duplicate
