### ISSUE TITLE
[BUG] Sherman integrated weapons not appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1954] opened 2022-04-20 03:25 UTC
<strong>Submitted At: </strong> 4/19/2022 22:25:51<br><br><strong>Issue: </strong><br> The Sherman mech is currently not displaying the ZF4 Solidcore or the Fuel Rod Gun in the "Active Mech Sheet" or "Active Mode" sections of the COMP/CON character sheet. This appears to be related to maximum weapon count: when the Nuclear Cavalier talent is removed from the character, the Sherman successfully displays the ZF4 Solidcore weapon on the Active Mech Sheet. <br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment] 2022-04-20 12:09
Duplicate of #1952

**Closed by msprijatelj** 2022-04-20 12:09 UTC
Labels: bug, triage, rules
