### ISSUE TITLE
[BUG] Superheavy mount core bonus cannot utilize flex mounts that come standard with the mecha as superheavy mounting

### ISSUE THREAD

**Issue by theian212** [massif-press/compcon#2381] opened 2024-03-09 20:55 UTC
**Describe the bug**
When I try to use a flex mount that comes standard with my mecha as the superheavy mounting for the mount that comes with superheavy mount core bonus it does not show up on the list of mounts available as options use as superheavy mounting

**To Reproduce**
1. Go to Your Mech in the Mech hanger
2. Click on Superheavy mount
3. Scroll down to The options it gives for you use as superheavy mounting

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vialra** [comment] 2024-03-13 08:31
Hey i could sadly not reproduce that issue, did you try it with different Mechs/Pilots?; what was the mech you tried it originally on?

What kind of error did comp/con provide? Could you attach a screenshot?

**Comment by msprijatelj** [comment] 2024-03-13 11:06
Yeah it would be good to know which frame this was on; if it was a frame with a Heavy Mount, the frame will be forced to use that mount for bracing.

**Comment by msprijatelj** [comment] 2024-03-15 16:10
Unable to reproduce this on mechs without Heavy mounts. Tested Superheavy Mounting with and without Improved Armament on Kidd and Minotaur, and Superheavy Mounting alone on Nelson. All Flex, Main, and Main/Aux mounts were valid mounts for bracing. Closing for now unless more information is provided (e.g. device, browser, CompCon version, as well as which Frame was used specifically).

**Closed by msprijatelj** 2024-03-15 16:10 UTC
Labels: bug, app

**Comment by vialra** [comment] 2024-03-15 16:35
Thx for testing all that ^^
