### ISSUE TITLE
[BUG] Empath I, Sympathetic Precognition, lacks the 1/scene limitation in its text

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1705] opened 2021-10-06 03:52 UTC
<strong>Submitted At: </strong> 10/5/2021 22:52:25<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> SYMPATHETIC PRECOGNITION
Your ability to sense the subjectivities of others grants you an uncanny ability to predict your ally’s actions, guiding them with your influence.

SYMPATHETIC PRECOGNITION
TRIGGER
An allied character in line of sight makes a skill check, attack, or save.
EFFECT
That character may choose not to roll, instead treating their check, attack, or save as if they had rolled a 10 on the d20.<br><br><strong>Correct Text/Data: </strong><br> SYMPATHETIC PRECOGNITION
Your ability to sense the subjectivities of others grants you an uncanny ability to predict your ally’s actions, guiding them with your influence. Gain the following reaction:

Sympathetic Precognition 1/scene, Reaction
Trigger: An allied character in line of sight makes a skill check, attack, or save.
Effect: That character may choose not to roll, instead treating their check, attack, or save as if they had rolled a 10 on the d20.<br>

**Comment by msprijatelj** [comment] 2021-10-06 10:50
Duplicate of

**Closed by msprijatelj** 2021-10-06 10:50 UTC
Labels: bug, triage, data
