### ISSUE TITLE
[BUG] NPC Roster Heading not in full view

### ISSUE THREAD

**Issue by darcwizrd** [massif-press/compcon#2332] opened 2023-11-09 02:48 UTC
As the title says, when I open up my NPC roster, I can't the top half of the header

![Screenshot 2023-11-08 at 21-45-34 COMP_CON](https://github.com/massif-press/compcon/assets/6514399/99b768eb-223b-49fe-8ea5-cc6620afcb86)

I'm working on Windows 10 in Firefox, Comp//Con ver. 2.3.19b

**Comment by msprijatelj** [comment] 2024-05-18 13:31
Duplicate of #2464

**Closed by msprijatelj** 2024-05-18 13:31 UTC
