### ISSUE TITLE
[BUG] General feedback

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2028] opened 2022-06-02 07:37 UTC
<strong>Submitted At: </strong> 6/2/2022 2:37:17<br><br><strong>Browser: </strong> Firefox and Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Theme constantly resetting, old pilots reappearing after deletion, mechs resetting to older version that were changed days ago.<br><br><strong>Reproduction Steps:<br> </strong> Theme randomly resets to default when navigating pages. Old Pilots reappearing in list at random after deleting them. Permanently deleting them hasn't stopped it from happening. Suspect its a cloud issue. Mechs constantly show up without changes made to them, at lower levels, or with different weapons that were changed days ago. Again I suspect its a cloud issue with how it rewrites the data.<br><br><strong>Expected Result:<br> </strong> I'd like this issue fixed, it makes the website super ponderous to use as I never know what versions of pilots or mechs I'll wind up with and the theme constantly changing is just plain annoying.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment] 2022-06-27 19:27
dupe of #1976

**Closed by jarena3** 2022-06-27 19:27 UTC
Labels: bug, triage, app
