### ISSUE TITLE
Feature Request: Expanded search categories

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1601] opened 2021-08-07 01:46 UTC
<strong>Submitted At: </strong>8/6/2021 20:46:27
<strong>Is your feature request related to a problem? Please describe. </strong>
As a new player, I cannot use compendium search to discover game rules and systems, since compendium search only covers Frames, Mech Systems, Mech Weapons and Weapon mods.
This is especially important as someone not already familiar with game vocabulary and abbreviations.

Examples:
"AP" returns no relevant results, does not return "Armor Piercing (AP)".
"Bonded" returns no results.
"critical hit" returns no results.
etc.
<strong>Describe the solution you'd like: </strong>
Search should be expanded to include most or all categories of the compendium.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment] 2021-08-09 18:35
duplicate of #1086

**Closed by jarena3** 2021-08-09 18:35 UTC
Labels: feature, triage
