### ISSUE TITLE
[BUG] undefined pilot data

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1811] opened 2022-01-02 15:34 UTC
<strong>Submitted At: </strong> 1/2/2022 9:34:24<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> All devices<br><br><strong>Issue Description: </strong><br> After logging in to my account, I get multiple errors when trying to view my playgroup's pilot roster.  Aside from mine, they don't show, and a "t.pilot is undefined" error shows up for each.<br><br><strong>Reproduction Steps:<br> </strong> Simply logging in.  Unsure if the HORUS theme would affect it, but that is the theme I'm using.<br><br><strong>Expected Result:<br> </strong> I expected to see my entire playgroup's pilot roster.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by okeegan** [comment] 2022-01-04 04:02
I also have this problem. Here is some more information that might help with debugging efforts:

- In my 'Pilot Roster' the 'Ungrouped' tab appears empty, but has (3) in the pilot count.
- Importing pilots via vault code is successful, but syncing with the cloud never succeeds; 3 of 6 pilots never sync.
  - `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sync.ts:108:28
    v sync.ts:108`
- Console errors are repeatedly:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/4075884/148007087-be2573a2-10d4-4863-a6e3-da309f9655cd.png">

I think somewhere along the line, one of the pilot's vault IDs changed or was deleted because the only 404 from the network requests is:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>protected/us-east-1:/pilot/572dfe6a-458b-461e-a0b5-c16f323230f3//7d7a9ea8-208d-4bc5-9fcb-d2feb3041ec4</Key><RequestId>E84CG4BV4B6D9HEW</RequestId><HostId>BU8S/+yHVp4Yelhtq6ssMcvCYxiOZfghgmR0vO5W5Xz36zWdinPny/1BV8p7xORgV66bSfQa/zk=</HostId></Error>`


When I manage to avoid adding the broken pilots to a mission through the mission runner, I then hit an error on the encounter view:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/4075884/148007966-00b188c8-1414-4234-9b30-4186d143179d.png">


Please let me know if I can get you more information. It's extremely reproducible on my end hah.

**Comment by jarena3** [comment] 2022-04-12 16:48
Fixed in 2.3

**Closed by jarena3** 2022-04-12 16:48 UTC
Labels: bug, triage, app
