### ISSUE TITLE
[BUG] My playgroup is having issues where everyone is on a different version of the program. I'm currently on 2.2.34, how do we get everyone updated to the same version?

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2042] opened 2022-06-26 03:57 UTC
<strong>Submitted At: </strong> 6/25/2022 22:57:43<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> on version 2.2.34 - other users in my group are on 2.3.8 - how do we all get it on the same update?<br><br><strong>Reproduction Steps:<br> </strong> Have tried numerous times to check for updates, no updates are being found.<br><br><strong>Expected Result:<br> </strong> I expect that when i hit check for updates that it finds them and updates.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-06-26 04:53
Workaround is described on this page: https://github.com/massif-press/compcon/wiki/FAQ%3A-Troubleshooting

Closing as duplicate of #1993

**Closed by msprijatelj** 2022-06-26 04:53 UTC
Labels: bug, triage, app
