### ISSUE TITLE
Bug Report: Every time Comp/Con is closed and re-launched, any created NPCs with the 'Reinforced' System are granted their +5HP again

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#430] opened 2019-12-12 13:44 UTC
<strong>Submitted At: </strong>12/12/2019 7:44:40
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Every time Comp/Con is closed and re-launched, any created NPCs with the 'Reinforced' System are granted their +5HP again
<strong>Reproduction Steps: </strong>Create an NPC with the Reinforced trait, close Comp/Con and relaunch it then open the profile of that NPC.
<strong>Contact Info: </strong>ZacmanTheDamned #4252

**Comment by aritsune** [comment] 2020-01-02 00:11
Duplicate of #413

**Closed by aritsune** 2020-01-02 00:11 UTC
Labels: bug
