### ISSUE TITLE
[BUG] [bug] pilot roster is entirely missing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1799] opened 2021-12-18 05:16 UTC
<strong>Submitted At: </strong> 12/17/2021 23:16:41<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> "ERROR:   e.pilotIDs is undefined" when I click the pilot roster button; there are no other options, just the blank COMP/CON page and the error message<br><br><strong>Reproduction Steps:<br> </strong> clicking "Pilot Roster" tab<br><br><strong>Expected Result:<br> </strong> access my list of Pilots and my active character/mech for the session<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
va/<@https://compcon.app/app.bundle.js:343:220523
ge@https://compcon.app/app.bundle.js:22:15925
va@https://compcon.app/app.bundle.js:343:220004
t.prototype._render@https://compcon.app/app.bundle.js:22:35296
i@https://compcon.app/app.bundle.js:22:64441
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un.prototype.run@https://compcon.app/app.bundle.js:22:27494
pn@https://compcon.app/app.bundle.js:22:25602
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
```<br>

**Comment by msprijatelj** [comment] 2021-12-18 17:05
Duplicate of #1785

**Closed by msprijatelj** 2021-12-18 17:05 UTC
Labels: bug, triage, app
