### ISSUE TITLE
Active: System Actions Not Resetting[BUG] 

### ISSUE THREAD

**Issue by Notanotherpatterngroup** [massif-press/compcon#2105] opened 2022-08-28 04:10 UTC
**Describe the bug**
While in Active mode, activating a system/deployable/etc. locks it as unavailable until it's switched out and back in through the Mech Hangar. Until then, the only way to use it is through the free action option; it's possible to use the 'undo' button to reset the status of the system but doing this and then re-using the action will mess up the action economy due to the system "refunding" an action that wasn't used. This persists between full repair and downtime menus; if a system has limited charges, these refresh as normal but the action's availability does not.

**To Reproduce**
1. Enter active mode with a mech whose systems carry a quick or full action [originally noticed with Flash Charges and Hunter Lock].
2. Use the system's action as normal, and end the round/start a new one.
4. The action should stay greyed out, even while the action economy has refreshed.

**Expected behavior**
System actions to refresh on the new turn/scene/applicable condition.

**Screenshots**
![image](https://user-images.githubusercontent.com/112298167/187056757-0f045fcc-8b8d-44c1-8df0-5f2cdace0351.png)
![image](https://user-images.githubusercontent.com/112298167/187056865-6e12fda3-3b56-4dfe-a418-3abe52907826.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 2.3.10

**Comment by msprijatelj** [comment] 2022-08-28 19:48
Duplicate of #2005

**Closed by msprijatelj** 2022-08-28 19:48 UTC
