### ISSUE TITLE
[BUG] Technophile talent issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1164] opened 2021-01-10 22:45 UTC
<strong>Submitted At: </strong>1/10/2021 16:45:38
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The Rank I  Technophile talent Servant-Class NHP cannot be removed from mechs, preventing the installation of better AI systems.
<strong>To Reproduce: </strong>
The gear menu for the Servant Class NHP doesn't have an option to remove the system. Also the system is automatically installed on every mech of the pilot with the talent.
<strong>Expected behavior: </strong>
The Servant Class NHP system needs to behave like any other system, rather than as an automatic, un-removable system.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment] 2021-02-22 20:40
duplicate of #671

**Closed by jarena3** 2021-02-22 20:40 UTC
Labels: bug, duplicate
