### ISSUE TITLE
[BUG] No Pilots in Microsoft Edge

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1792] opened 2021-12-12 23:15 UTC
<strong>Submitted At: </strong> 12/12/2021 17:15:42<br><br><strong>Browser: </strong> Edge<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> After clicking the pilot roster off the main menu, the top bar displays, (back, forth, home, compendium, etc.) but the rest of the page is blank. Error displays: "ERROR:   Cannot read properties of undefined (reading 'length')"<br><br><strong>Reproduction Steps:<br> </strong> Open Comp/Con, click Pilot Roster<br><br><strong>Expected Result:<br> </strong> Pilot Roster displays as it does on other browsers<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> STACK TRACE
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js:22:15925)
    at a.va (https://compcon.app/app.bundle.js:343:220004)
    at a.t._render (https://compcon.app/app.bundle.js:22:35296)
    at a.i (https://compcon.app/app.bundle.js:22:64441)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at new un (https://compcon.app/app.bundle.js:22:26528)
    at t (https://compcon.app/app.bundle.js:22:64455)
    at a.kn.$mount (https://compcon.app/app.bundle.js:22:64602)
    at init (https://compcon.app/app.bundle.js:22:19337)<br>

**Comment by msprijatelj** [comment] 2021-12-13 00:17
Duplicate of #1785

**Closed** 2021-12-13 00:17 UTC
Labels: bug, triage, app
