### ISSUE TITLE
Feature Request: Add pilot groups for managing multiple games

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#456] opened 2020-01-09 20:39 UTC
<strong>Submitted At: </strong>1/9/2020 14:39:55
<strong>Feature: </strong>Add pilot groups for managing multiple games
<strong>Details: </strong>Most of our group has been sharing pilot details. However there is no way to group pilots together by the campaign they play in. 

It would be nice to be able to create a group, name it, and add pilots to it, which would then show up as a collapsible category on the pilot screen. It would make switching between multiple games much easier. 

I didn't see anything like this in the roadmap yet. Apologies if it is already in consideration. 
<strong>Contact: </strong>Zutsutsu#0130

**Comment by aritsune** [comment] 2020-01-10 15:53
dupe of #380 and/or #419

**Closed by aritsune** 2020-01-10 15:53 UTC
Labels: enhancement
