### ISSUE TITLE
[BUG] Can't add image to Pilot, Mech, or NPC

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#879] opened 2020-06-02 00:57 UTC
<strong>Submitted At: </strong>6/1/2020 19:57:21
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Hitting [SET IMAGE] causes the following compcon error:
ERROR: Network Error

And the following Chrome Console error:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
<strong>To Reproduce: </strong>
Open a Pilot/Mech/NPC -- > [SET PILOT PORTRAIT] --> Upload an Image --> [SET IMAGE]
<strong>Expected behavior: </strong>
Uploading an Image and hitting [SET IMAGE] will set the image!
<strong>Additional context: </strong>
This happens on Pilots/Mechs/NPCs with existing images, as well as brand new ones that have no images
<strong>Contact Info: </strong>
Fibby#6376
<strong>Stack Trace: </strong>
```
Vue error at [cc-btn]
Error: Network Error
    at t.exports (https://compcon.app/app.bundle.js:85:23677)
    at XMLHttpRequest.m.onerror (https://compcon.app/app.bundle.js:85:22642)```

**Comment by jarena3** [comment] 2020-06-05 14:08
dupe of #859

**Closed by jarena3** 2020-06-05 14:08 UTC
Labels: bug, duplicate, triage
