### ISSUE TITLE
[BUG] Pilots missing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1800] opened 2021-12-19 23:32 UTC
<strong>Submitted At: </strong> 12/19/2021 17:32:53<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Cannot access saved pilots, not appearing in the pilot roster<br><br><strong>Reproduction Steps:<br> </strong> Updated comp/con and resynced pilot data<br><br><strong>Expected Result:<br> </strong> There should be 8 pilots listed in the pilot roster<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
e.prototype.LOAD_PILOTS@https://compcon.app/app.bundle.js:52:19292
m/i.mutations[e]@https://compcon.app/app.bundle.js:66:5528
f/</<@https://compcon.app/app.bundle.js:233:478038
p.prototype.commit/</<@https://compcon.app/app.bundle.js:239:638
p.prototype.commit/<@https://compcon.app/app.bundle.js:239:616
p.prototype._withCommit@https://compcon.app/app.bundle.js:239:2446
p.prototype.commit@https://compcon.app/app.bundle.js:239:590
p/this.commit@https://compcon.app/app.bundle.js:233:475503
e.prototype.loadPilots/A</<@https://compcon.app/app.bundle.js:52:22112
l/s/</<@https://compcon.app/app.bundle.js:37:2228
l/s/<@https://compcon.app/app.bundle.js:37:2333
a@https://compcon.app/app.bundle.js:37:1072
```<br>

**Comment by msprijatelj** [comment] 2021-12-20 02:58
Sounds like a duplicate of #1785

**Closed by msprijatelj** 2021-12-20 02:58 UTC
Labels: bug, triage, app
