### ISSUE TITLE
Share Code Error (Failing to Generate)

### ISSUE THREAD

**Issue by JakkieBoi** [massif-press/compcon#2200] opened 2023-03-09 22:56 UTC
**Describe the bug**
It won't allow me to generate a share code for any of my pilots, new or old.

**To Reproduce**
1. Click "get share code" anywhere it is available
2. Click "Generate Pilot Share Code"
3. Wait
4. Error shows up on bottom left "An error occurred while attempting to generate a share code"

**Screenshots**
![image](https://user-images.githubusercontent.com/127452818/224178831-fc0503ca-6ce3-4c14-893b-ab12df001653.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 111.0.5563.65

**Comment by msprijatelj** [comment] 2023-03-09 23:03
Duplicate of #2199

**Closed by msprijatelj** 2023-03-09 23:03 UTC
