### ISSUE TITLE
Feature Request: NPC table sortable by stats

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1148] opened 2021-01-05 14:49 UTC
<strong>Submitted At: </strong>1/5/2021 8:49:46
<strong>Is your feature request related to a problem? Please describe. </strong>
The PC Mechs table (Compendium/Frames) can be sorted by Highest to Lowest Size/Armour/HP etc. It is annoying when trying to find NPCs to fill specific roles in an encounter that I cannot sort them by stat in the NPC class table (Compendium/NPC Classes)
<strong>Describe the solution you'd like: </strong>
Have the NPC classes table sortable by stat in the same way the PC Frames table is.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment] 2021-02-12 19:11
duplicate of #840

**Closed by jarena3** 2021-02-12 19:11 UTC
Labels: duplicate, feature, triage
