### ISSUE TITLE
[BUG] full tech actions don't get the roller window

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1214] opened 2021-01-20 15:44 UTC
<strong>Submitted At: </strong>1/20/2021 9:44:50
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
activating a full tech action that has a tech attack (e.g. last argument of kings) doesn't bring up the automatic roller
<strong>To Reproduce: </strong>
use a full action to do a full tech
choose a full tech action that has a tech attack (e.g. last argument of kings, predator/prey concepts, slave systems)
<strong>Expected behavior: </strong>
the automatic roller that comes up when performing a skirmish or invade should appear
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by TranslucentSabre** [comment] 2021-06-09 20:01
@jarena3, this is effectively a duplicate of #1317 and was resolved at the time that one was.

**Closed** 2021-06-10 12:25 UTC
Labels: bug
