### ISSUE TITLE
[BUG] Unable to export Comp/Con info

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#825] opened 2020-04-29 16:47 UTC
<strong>Submitted At: </strong>4/29/2020 11:47:27
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Trying to export all comp/con data does not actually create a file during export.
<strong>To Reproduce: </strong>
Go into options, export all comp/con data, select file location. The file is not created.
<strong>Expected behavior: </strong>
Comp/Con data should be exported.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
None available.

**Comment by jarena3** [comment] 2020-04-29 17:20
duplicate of #773

**Closed by jarena3** 2020-04-29 17:20 UTC
Labels: bug, duplicate
