### ISSUE TITLE
[BUG] Cloud ID not generating through share code

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#598] opened 2020-02-04 03:01 UTC
<strong>Submitted At: </strong>2/3/2020 21:01:40
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Trying to use cloud saves, but the ID doesn't generate once the share code is passed on and input into the app.  So it's unable to sync, and doesn't have any ID for the second person
<strong>To Reproduce: </strong>
Had friend make an ID and send it my way, once imported using Cloud saves, the pilot's data was entirely there except for my friends Cloud ID.  

Had them create a new ID, made sure to save their data a 2nd time, then send it with the new one. No change.  I am unable to sync the pilot to any existing cloud on my end. 
<strong>Expected behavior: </strong>
For the cloud save to be imported, and be able to have their changes sync over to my system through the cloud. 
<strong>Additional context: </strong>
Got help by lovely devs on Discord. Asked to make this. 'o' 
<strong>Contact Info: </strong>
@Sennastin in the Discord.

**Comment by Eranziel** [comment] 2020-02-04 03:47
Two problems:
- [ ] Cloud ID gets wiped automatically on import. In order for quick sync feature to work as intended, the cloud ID should be retained until/unless user creates a new cloud save.
- [ ] When creating a cloud save for the first time, the pilot has no cloud ID because the ID comes from the gist API response. Either the user needs to cloud save once more manually after creating the cloud save, or we need to do a gist save after the gist new finishes.

**Comment by jarena3** [comment] 2020-02-04 15:41
fixed in https://github.com/massif-press/compcon/pull/602

**Closed** 2020-02-04 23:48 UTC
Labels: bug, complete
