### ISSUE TITLE
[BUG] Gilgamesh +1 Limited Passive Not Counting?

### ISSUE THREAD

**Issue by iwriterobots** [massif-press/compcon#2497] opened 2024-08-16 18:46 UTC
Hello! It seems to me that the +1 limited use passive of the Gilgamesh frame isn't being counted by limited systems/weapons or is at least causing an issue in counting limited uses. I've attached pictures that show in more detail the issue. This system has Limited 2 at base, but is only receiving a bonus of +1 from my stats/passives, despite my stats and frame granting a +2 overall. So it should be Limited 4.

To reproduce this bug just create a pilot with 2 or more points in Engineering, then create a Gilgamesh mech for said pilot. I've tried this with all ranges of points in Engineering, testing different ranges of bonuses to Limited systems, and the Limited tag's tool tip always seems to be incorrect by 1-2.

![image](https://github.com/user-attachments/assets/a9001aec-d652-4231-9e08-28e96ffe13ae)
![image](https://github.com/user-attachments/assets/351ec56f-7f5f-4016-b7e4-37c29e0dd499)
(These images are from the same Pilot/Mech pairing, and you can see that the tooltip displays "Limited 2 + 1 bonus" where it should be getting a +2 bonus)

I've tested this and had the same result on different windows computers across both Chrome and Firefox browsers.

Hope this helps!

**Comment by msprijatelj** [comment] 2024-08-16 18:49
Duplicate of #2496

**Closed by msprijatelj** 2024-08-16 18:49 UTC
