### ISSUE TITLE
[BUG] Ushabti Omnigun round refresh

### ISSUE THREAD

**Issue by Matvakama** [massif-press/compcon#2279] opened 2023-07-05 22:51 UTC
Ushabti Omnigun doesn't refresh at the start of each round in Active Mode.

**To Reproduce**
1. Make a Pegasus mech.
2. Go into Active Mode, start combat
3. Use Omnigun.
4. Complete turn.
5. Start next round. Omnigun doesn't refresh unlike other free actions, e.g. Overcharge.

**Expected behavior**
Ushabti Omnigun would refresh at the start of each round once the "Start Round X" is selected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 114.0.2

**Additional context**

**Comment by msprijatelj** [comment] 2023-07-06 02:47
Duplicate of #2005

**Closed by msprijatelj** 2023-07-06 02:47 UTC
