### ISSUE TITLE
[BUG] Can't sort NPC Classes by stats

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1775] opened 2021-12-07 20:35 UTC
<strong>Submitted At: </strong> 12/7/2021 14:35:49<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> On the "NPC Classes" page in the Compendium, sorting by any column that is not 'Class' or 'Role' does not work (e.g., Armor, Evade, Save)<br><br><strong>Reproduction Steps:<br> </strong> - Navigate to the "NPC Classes" page in the Compendium: https://compcon.app/#/compendium/npc_classes
- Click any column that is not 'Class' or 'Role' to sort by that column
- The classes are not sorted<br><br><strong>Expected Result:<br> </strong> The classes to be sorted by the selected column<br><br><strong>Additional Context:<br> </strong> C/C v2.2.34<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2021-12-07 22:06
Duplicate of #840

**Closed** 2021-12-07 22:06 UTC
Labels: bug, triage, app
