### ISSUE TITLE
[BUG] Leviathan Heavy Assault Cannon issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1504] opened 2021-06-30 17:55 UTC
<strong>Submitted At: </strong> 6/30/2021 12:55:54<br><br><strong>Issue: </strong><br> Noticed when in Active Mode. Leviathan HAC has two modes: Standard and Spin-Up Modes. When going to make an attack with the Leviathan using Standard Mode, there is no Skirmish button, only the Barrage option. Additionally, when using the Quick Action button on the bottom ribbon of Active Mode to Skirmish, the Leviathan Standard Mode isn't one of the Skirmish weapon options. RAW state that "unlike other Superheavy weapons, the Leviathan can be used with Skirmish," provided it is not in Spin-Up Mode. Would like to see the option for this corrected to reflect ability to Skirmish with it.<br><br><strong>Massif Reference: </strong> Lancer Core Book pg. 135<br>

**Comment by jarena3** [comment] 2021-07-16 18:11
Duplicate of #1481

**Closed by jarena3** 2021-07-16 18:11 UTC
Labels: bug, rules, triage
