### ISSUE TITLE
[BUG] Sorting doesn't work for NPC Classes

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1252] opened 2021-02-09 17:13 UTC
<strong>Submitted At: </strong>2/9/2021 11:13:23
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Sorting NPC template classes by anything other than Role or Name (i.e. Heat Cap or Armor) does not work.  Arrows appear as if it is sorting, but the list does not sort.
<strong>To Reproduce: </strong>
Go to the NPC Classes list from the Compendium. Try to sort.
<strong>Expected behavior: </strong>
It sorts good!
<strong>Additional context: </strong>
I love tables
<strong>Contact Info: </strong>
Shoe#2433
<strong>Stack Trace: </strong>
Nothing in error log

**Comment by jarena3** [comment] 2021-02-12 19:11
duplicate of #840

**Closed by jarena3** 2021-02-12 19:11 UTC
Labels: bug, duplicate, triage
