### ISSUE TITLE
[BUG] NPC Optional Systems 'stuck' on an option

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#795] opened 2020-04-20 00:59 UTC
<strong>Submitted At: </strong>4/19/2020 19:59:39
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When picking optional systems for an NPC (specifically a T1 Pirate-Commander-Demolisher) the stat block for systems (range, damage, effect etc) became stuck and would not update when clicking on other systems.
<strong>To Reproduce: </strong>
I'm not sure if it applies to all NPCs/Templates, but I created a Tier 1 Pirate-Commander-Demolisher, and when picking optional systems I clicked on the Boarding Leash system. After this the stat block for all other systems only showed the stat block for the Boarding Leash, and each time gave the error message "ERROR: t.item.Damage is not a function". 

This error continues even after closing the optional systems menu, until you click Boarding Leash again to deselect it, or exit the dialogue and choose a new NPC and then go back to the original 'broken' one.
<strong>Expected behavior: </strong>
The optional systems dialogue for NPCs should show the stat block for the currently selected system.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
```
Vue error at [cc-npc-weapon-card]
i@https://compcon.app/app.bundle.js:101:136179
t.prototype._render@https://compcon.app/app.bundle.js:22:35299
i@https://compcon.app/app.bundle.js:22:64447
un.prototype.get@https://compcon.app/app.bundle.js:22:26613
un.prototype.run@https://compcon.app/app.bundle.js:22:27497
pn@https://compcon.app/app.bundle.js:22:25605
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
```

**Comment by aritsune** [comment] 2020-04-20 02:23
Can't reproduce and neither can the original reporter anymore, so closing

**Comment by aritsune** [comment] 2020-04-26 16:55
#807

**Closed** 2020-04-27 15:59 UTC
Labels: bug
