### ISSUE TITLE
[BUG] Pilot Callsigns Cut Off at Last Character

### ISSUE THREAD

**Issue by LonePaladin** [massif-press/compcon#2224] opened 2023-04-27 22:07 UTC
**Describe the bug**
When viewing a pilot sheet, their callsign (in big letters at the top) is always cut off with an ellipsis as the last character -- even if the callsign is only four letters. It only appears to affect characters shared via share code.

**To Reproduce**
1. Import a pilot with a share code.
2. Open the pilot's dossier.
3. Notice the ... at the end of their callsign.

**Expected behavior**
I expected to see `HAWK`, not `HAW...`.

**Screenshots**
A newly-created pilot on my end:
![image](https://user-images.githubusercontent.com/37523352/235000801-6fdc6b77-060b-4ee6-add2-360660fbcfea.png)

An imported pilot, callsign "Borealis":
![image](https://user-images.githubusercontent.com/37523352/235000880-ce701b1f-bd12-426e-a677-420fcf163e37.png)

Another pilot, callsign "Hawk":
![image](https://user-images.githubusercontent.com/37523352/235001282-0f27e122-0ef1-4616-a6d0-d52de58a0b2c.png)

**Desktop (please complete the following information):**
 - **OS:** Windows 11
 - **Browser:** Firefox
 - **Version:** 112.0.2

**Additional context**
This seems to be isolated to pilots imported from other users.

**Comment by msprijatelj** [comment] 2023-04-27 22:10
Duplicate of #2223 , collecting there

**Closed by msprijatelj** 2023-04-27 22:10 UTC
