### ISSUE TITLE
[BUG] OSIRIS NHP not accessible

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1944] opened 2022-04-18 00:55 UTC
<strong>Submitted At: </strong> 4/17/2022 19:55:26<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Third license level on Horus Goblin attained; Osiris NHP not accessible/visible at all<br><br><strong>Reproduction Steps:<br> </strong> Persistent issue<br><br><strong>Expected Result:<br> </strong> I expected to be able to add the Osiris NHP to my mech build<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2022-04-18 16:33
Cannot reproduce on CompCon version 2.3.4 on Chrome Desktop.  I created a new pilot, set them to LL3, picked out Goblin 3, then navigated to Mech Hangar.  OSIRIS-Class NHP was available in all 3 possible view modes when selecting a system when it was previously unequipped (since the Unique tag hides the system when one is already equipped).  The user may have had another AI already equipped on their mech without having Lesson of Shaping or a similar bonus equipped, since once the AI cap is reached, another AI cannot be equipped. Closing for now.

**Closed by msprijatelj** 2022-04-18 16:33 UTC
Labels: bug, triage, app
