### ISSUE TITLE
[BUG] Covering Fire not in active pilot page

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1807] opened 2021-12-31 12:54 UTC
<strong>Submitted At: </strong> 12/31/2021 6:54:44<br><br><strong>Issue: </strong><br> The reaction for Covering Fire does not show up in the active sheet. It's really tedious to have to open up the game's rules for something quick which should 100% be on an abilities summary.<br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment] 2022-01-04 14:52
Duplicate of #1808

**Closed by msprijatelj** 2022-01-04 14:52 UTC
Labels: bug, triage, rules
