### ISSUE TITLE
[BUG] Unable to reset to default compcon

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1675] opened 2021-09-18 00:21 UTC
<strong>Submitted At: </strong> 9/17/2021 19:21:50<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Any change I make to the compcon "structure" (lcps, cloud settings...) are reverted on a refresh of the page, and clicking the button to delete every compcon data does nothing<br><br><strong>Reproduction Steps:<br> </strong> i honestly have no idea<br><br><strong>Expected Result:<br> </strong> Compcon should have those carry over inbetween refreshes<br><br><strong>Additional Context:<br> </strong> I tried deleting the cache and it still had lcps installed<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'push')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:52:56601
    at Array.forEach (<anonymous>)
    at new t (https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:52:56552)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:52:11421
    at Array.map (<anonymous>)
    at Object.get (https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:52:11305)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:66:2301
    at https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:233:478335
    at kn.<anonymous> (https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:233:476219)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=21fb61f653957588c5a3:22:26610)```<br>

**Comment by msprijatelj** [comment] 2021-10-09 16:23
Duplicate of #1710

**Closed by msprijatelj** 2021-10-09 16:23 UTC
Labels: bug, triage, app
