### ISSUE TITLE
[BUG] Compendium NPC Classes mostly fails to Sort

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1634] opened 2021-08-20 05:41 UTC
<strong>Submitted At: </strong> 8/20/2021 0:41:48<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The NPC Classes page in the Compendium is only able to sort by Class and Role. Clicking different headings (HP, Armor, etc.) does not sort the data, but does highlight the column header and display arrows indicating ascending/descending. <br><br><strong>Reproduction Steps:<br> </strong> Bug was originally encountered w/ several custom lcps installed, then recreated as follows:

Open compcon.app/#/ in incognito mode (for a fresh load). Click Content Manager, then Install Content. Select and Install the "Lancer Core Book NPCs" (Version 1.0.4).  Make sure the Lancer Core NPCS content pack is marked Active, then exit to the main menu.

Click Compendium. Click NPC Classes. You should see a table of NPC Classes. Try to sort the table by clicking the various headers: Class, Role, HP, Armor, Struct., HeatCap., Stress, Evade, E-Def, Speed, Sensor, & Save. <br><br><strong>Expected Result:<br> </strong> The clicked column headers will bold, show a red background, and add an indicator arrow to imply the content is sorted. The content will not sort by any column to the right of Role (HP, Armor, etc.). 

Attempting to sort by Class and Role will function as intended.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment] 2021-08-20 11:57
Duplicate of #840

**Comment by msprijatelj** [comment] 2021-08-20 11:57
Duplicate of #840

**Closed by msprijatelj** 2021-08-20 11:57 UTC
Labels: bug, triage, app
