### ISSUE TITLE
[BUG] Using Limited Systems in Active Mode doesn't allow for repeat uses on later turns

### ISSUE THREAD

**Issue by CapnRis** [massif-press/compcon#2187] opened 2023-02-13 04:14 UTC
**Describe the bug**
When using Active Mode with a mech using a Limited System such as Pattern-B Hex Charges or Spike Charges, using an action from these systems will grey out the options for that action, and will not become available to use on later rounds or if combat mode is ended and begun again. If the "Free Action" option is chosen for a Mine charge, or the mine's notation in the Deployed Equipment section is removed, the standard option for the Mine charge becomes blue and usable again; no in-system methods of restoring Grenade option functionality were found. Reloading the browser page will clear the problem and make all System action options available again, but also undoes operations made since the previous round change.

**To Reproduce**
1. Select a Pilot and Mech equipped with at least one system with the Limited, Grenade and Mine tags.
2. Open Active Mode, and enter Combat Mode.
3. Select an action from the system(s) mentioned above. 
4. End turn and round.
5. Previously used Grenade/Mine options remain grey and unavailable for use. Problem persists if combat is ended and resumed, or if mission is ended and a new one started.

**Expected behavior**
As systems with the Grenade and Mine tags are meant to be usable multiple times during a mission within their Limited quantity, the tracker should make the options to use them available again with the start of a new round or combat as long as there are remaining charges, as with other systems or weapons. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome v110.0.5481.77
 - C/C Version: 2.3.11

**Additional context**
A previous mention of this problem appears to have been posted to the Pilot NET discord on 01/01/2023, but despite recommendation given at the time, I could not find an existing bug report for the issue.

**Comment by msprijatelj** [comment] 2023-02-13 14:52
Duplicate of #2005

**Closed by msprijatelj** 2023-02-13 14:52 UTC
