### ISSUE TITLE
[BUG]  ERROR:   Cannot read properties of undefined (reading 'length') 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1786] opened 2021-12-11 17:17 UTC
<strong>Submitted At: </strong> 12/11/2021 11:16:57<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When clicking "Pilot Roster", getting the error " ERROR:   Cannot read properties of undefined (reading 'length') "<br><br><strong>Reproduction Steps:<br> </strong> Clicking to open the Pilot Roster<br><br><strong>Expected Result:<br> </strong> Pilot roster should open<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220548
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:15925)
    at a.va (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:343:220004)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:35296)
    at a.i (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64441)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26610)
    at new un (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:26528)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64455
    at a.$mount (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:64602)
    at init (https://compcon.app/app.bundle.js?__WB_REVISION__=9832985de464f7222ea4:22:19337)```<br>

**Comment by msprijatelj** [comment] 2021-12-12 03:25
Duplicate of #1785

**Closed by msprijatelj** 2021-12-12 03:25 UTC
Labels: bug, triage, app
