### ISSUE TITLE
[BUG] Import pilot data fails with `e.Questions is undefined`

### ISSUE THREAD

**Issue by smangham** [massif-press/compcon#2007] opened 2022-05-14 19:49 UTC
**Describe the bug**
Attempting to import a pilot via share code fails, apparently due to bond data.

**To Reproduce**
1. Go to "Import pilot" -> "Import from share code", enter `YMRC6U`
2. Click on "Search"
3. Click on "Import as *a remote resource*"
```
TypeError: e.Questions is undefined
    set Bond https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    Deserialize https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    Update https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    Deserialize https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    importAsRemote https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    click https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    n https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    $emit https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    click https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:40
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    n https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    _wrapper https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Qi https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    St https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    to https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    S https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    f https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Mi https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    _update https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    r https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    get https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    rr https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Dn https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    $mount https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    init https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    p https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    f https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    b https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    f https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    b https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    f https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Mi https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    _update https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    r https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    get https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    run https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Zn https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    mt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    ut https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    promise callback*at https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    mt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    tr https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    update https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    notify https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    set https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    set https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    stageImport https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    downloadPilotData https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    promise callback*downloadPilotData https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    searchResults https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    run https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    Zn https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    mt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    ut https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    promise callback*at https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    mt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    tr https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    update https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    notify https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    set https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    set https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    search https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    promise callback*search https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    click https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    n https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    $emit https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    click https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:40
    rt https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    n https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
    _wrapper https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7
739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:326158

```

**Expected behavior**
The import to work (or, actually, to fail because it uses a talent from Operation Solstice Rain and my test account didn't have that). The pilot does have questions answered.

**Screenshots**
![questions](https://user-images.githubusercontent.com/8093436/168446060-6d98cdc2-945d-42b4-8ec6-58f88760ac5a.png)

**Desktop (please complete the following information):**
 - **OS:** Windows 11 64-bit
 - **Browser:** Firefox
 - **Version:** 100.0

**Additional context**
This pilot was made before the tweaks to Major/Minor bond presentation.

**Comment by wisq** [comment] 2022-06-01 22:32
I was writing up a bug report, but then I realised it's a duplicate of this bug.  Here's what was going to be in my report:

**Describe the bug**
Loading a pilot with bond data will cause a JavaScript error if KTB data is not installed.

Note that this is NOT the usual helpful error telling the user which LCPs to install, it's just a "please check the console log" error.

**To Reproduce**
(from a fresh COMP/CON install)
1. Install KTB data in content manager
2. Create a pilot, level it up to LL1, assign it a bond
3. Export the pilot
4. Delete (or disable? not tested) the KTB data in content manager
5. Try to import the pilot

**Expected behavior**
An error message that indicates the user needs to install the KTB LCP (or other bond data).

**Screenshots**
![CON-20220601-182754](https://user-images.githubusercontent.com/255758/171512169-c2d6f593-e30c-4cbc-af25-5f0d37d8c887.jpg)

The exact error varies depending on whether the pilot has filled-in data, I think?  For this pilot, I forgot to fill in the bond questions.  For my actual campaign pilot (with a proper bond setup), it was

```
TypeError: Cannot read properties of undefined (reading 'length')
    at set Bond [as Bond] (739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:724952)
    at r.Deserialize (739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:727845)
    at Pilot.Update (739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:327625)
    at Pilot.Deserialize (739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:326134)
```

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Browser: Chrome 102.0.5005.61 x86_64

**Closed** 2022-06-28 22:50 UTC
